services:
  - type: web
    name: genericbro-backend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y build-essential cargo libssl-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn run:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true